# Use Node image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --only=production
COPY . .

# Create the logs
RUN mkdir -p logs

# Expose port
EXPOSE 8080

# Start the server
CMD ["node", "server.js"]
